import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-24 sm:pt-28 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <div className="rounded-2xl border border-white/10 bg-white/[0.02] backdrop-blur-sm p-6 sm:p-10">
            <h1 className="font-display text-3xl sm:text-4xl font-bold text-white mb-2">
              Terms of Service
            </h1>
            <p className="text-sm text-white/30 mb-8">Last updated: March 27, 2026</p>

            <div className="prose-invert space-y-6 text-sm sm:text-base text-white/60 leading-relaxed">
              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  1. Agreement to Terms
                </h2>
                <p>
                  By accessing or using KIN (&quot;the Service&quot;), operated by KR8TIV (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;),
                  you agree to be bound by these Terms of Service. If you do not agree to these terms,
                  please do not use the Service.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  2. Description of Service
                </h2>
                <p>
                  KIN is an AI companion platform that provides personalized artificial intelligence
                  companions accessible through Telegram and our web application. Each companion has
                  a unique personality and set of skills designed to assist users with various tasks
                  including but not limited to conversation, creative projects, and personal organization.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  3. User Accounts
                </h2>
                <p>
                  To use KIN, you must authenticate through Telegram. You are responsible for maintaining
                  the security of your Telegram account and any activity that occurs under your account.
                  You must be at least 13 years of age to use the Service.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  4. AI Companion Interactions
                </h2>
                <p>
                  AI companions are artificial intelligence programs and not human beings. While companions
                  are designed to be helpful and personalized, their responses are generated by machine
                  learning models and may not always be accurate, complete, or appropriate. You should
                  not rely on companion output for medical, legal, financial, or other professional advice.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  5. Subscription and Payments
                </h2>
                <p>
                  KIN offers free and paid subscription tiers. Paid subscriptions are billed monthly
                  and can be cancelled at any time. Refunds are available within 7 days of purchase.
                  We reserve the right to modify pricing with 30 days advance notice.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  6. Acceptable Use
                </h2>
                <p>
                  You agree not to use the Service to generate harmful, illegal, abusive, or misleading
                  content. We reserve the right to suspend or terminate accounts that violate these terms
                  or engage in behavior that disrupts the Service or harms other users.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  7. Intellectual Property
                </h2>
                <p>
                  Content you create through interactions with your AI companion remains yours. The KIN
                  platform, including its design, code, and AI models, is the intellectual property of
                  KR8TIV and is protected by applicable intellectual property laws.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  8. Limitation of Liability
                </h2>
                <p>
                  KIN and KR8TIV are provided &quot;as is&quot; without warranties of any kind. We are not liable
                  for any damages arising from your use of the Service, including but not limited to
                  direct, indirect, incidental, or consequential damages.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  9. Changes to Terms
                </h2>
                <p>
                  We may update these Terms of Service from time to time. We will notify users of
                  material changes through the Service or via email. Continued use of the Service
                  after changes constitutes acceptance of the updated terms.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white/90 mb-3">
                  10. Contact
                </h2>
                <p>
                  For questions about these Terms of Service, please reach out through our Telegram
                  bot or contact us at support@kin.kr8tiv.com.
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
